### ISSUE TITLE
cmake error when installing/exporting target that uses tbb

### ISSUE THREAD

**Issue by pwm1234** [justusc/FindTBB#5]
I just ran into a problem using the FindTBB tbb target. When I put tbb into the target link libraries of my project, I was getting a cmake error (well it was printed out as an error, but the cmake configure step seemed to generate everything) when calling install export. The error said that I was "exporting a target that had a dependency on the tbb target which was not also exported." I think this is because the tbb target is made with an add_library call for a real library rather than an imported library. I made a pull request with changes that made this error/warning go away.

**Comment by justusc** [comment]
Fixed
